# Form implementation generated from reading ui file 'FirstWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 736)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.historyButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.historyButton.setGeometry(QtCore.QRect(920, 600, 161, 61))
        self.historyButton.setObjectName("historyButton")
        self.clearButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(740, 600, 161, 61))
        self.clearButton.setObjectName("clearButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(101, 11, 929, 50))
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(430, 290, 191, 131))
        self.startButton.setObjectName("startButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.historyButton.setText(_translate("MainWindow", "История игр"))
        self.clearButton.setText(_translate("MainWindow", "Очистить историю игр"))
        self.label.setText(_translate("MainWindow", "Перед вами будут появляться слова, и вам нужно будет нажимать на кнпку \"Новое\", если слово уже появлялось и \"Было\", если слово появлялось до этого"))
        self.startButton.setText(_translate("MainWindow", "Начать"))
